---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop
    - watch
    - rsync
    - tree

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - phpstorm
    - webstorm
    - sequel-pro
    - java
